stages:
  train:
    foreach:
      - model-1
      - model-2
    do:
      cmd: python train.py
      wdir: ${item}
      params:
        - params.yaml:
      deps:
      - train.py
      - data
      metrics:
      - ../dvclive/${item}/metrics.json:
          cache: false
      plots:
      - ../dvclive/${item}/plots/metrics/acc.tsv:
          cache: false
          x: step
          y: acc
  evaluate:
    cmd: python evaluate.py
    deps: 
    - dvclive
    metrics:
    - evaluation/metrics.json:
        cache: false

